package renderer

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/fatih/color"
	"github.com/smford/tf-blast/pkg/analyzer"
)

// RenderDiffTerminal outputs colorized differential blast-radius analysis to terminal.
func RenderDiffTerminal(w io.Writer, diff *analyzer.DiffReport) error {
	if diff == nil {
		return nil
	}

	red := color.New(color.FgRed, color.Bold).SprintFunc()
	green := color.New(color.FgGreen, color.Bold).SprintFunc()
	yellow := color.New(color.FgYellow, color.Bold).SprintFunc()
	whiteBold := color.New(color.FgWhite, color.Bold).SprintFunc()
	gray := color.New(color.FgHiBlack).SprintFunc()

	fmt.Fprintln(w)
	fmt.Fprintf(w, "%s\n\n", whiteBold("📊 Plan Comparison & Risk Delta:"))

	// Delta indicators
	radiusDeltaStr := fmt.Sprintf("%+d", diff.RadiusDelta)
	if diff.RadiusDelta < 0 {
		radiusDeltaStr = green(radiusDeltaStr)
	} else if diff.RadiusDelta > 0 {
		radiusDeltaStr = red(radiusDeltaStr)
	}

	scoreDeltaStr := fmt.Sprintf("%+d", diff.ScoreDelta)
	if diff.ScoreDelta < 0 {
		scoreDeltaStr = green(scoreDeltaStr)
	} else if diff.ScoreDelta > 0 {
		scoreDeltaStr = red(scoreDeltaStr)
	}

	fmt.Fprintf(w, "  %s %d -> %d (%s)\n",
		gray("Blast Radius:"),
		diff.BeforeSummary.TotalBlastRadius,
		diff.AfterSummary.TotalBlastRadius,
		radiusDeltaStr,
	)
	fmt.Fprintf(w, "  %s  %d -> %d (%s)\n",
		gray("Blast Score: "),
		diff.BeforeSummary.BlastScore,
		diff.AfterSummary.BlastScore,
		scoreDeltaStr,
	)
	fmt.Fprintf(w, "  %s    %d -> %d (%+d)\n\n",
		gray("Total Changes:"),
		diff.BeforeSummary.TotalChanges,
		diff.AfterSummary.TotalChanges,
		diff.ChangesDelta,
	)

	// Resolved risks
	if len(diff.ResolvedRisks) > 0 {
		fmt.Fprintf(w, "%s (%d resolved):\n", green("✅ Mitigated / Resolved Risks"), len(diff.ResolvedRisks))
		for _, r := range diff.ResolvedRisks {
			fmt.Fprintf(w, "  - %s: %s was %s (%s)\n",
				green("RESOLVED"),
				r.Address,
				r.Action,
				r.Severity,
			)
		}
		fmt.Fprintln(w)
	}

	// New risks
	if len(diff.NewRisks) > 0 {
		fmt.Fprintf(w, "%s (%d introduced):\n", red("⚠️  Newly Introduced Risks"), len(diff.NewRisks))
		for _, r := range diff.NewRisks {
			fmt.Fprintf(w, "  + %s: %s planned %s (%s, score +%d)\n",
				red("NEW"),
				r.Address,
				r.Action,
				r.Severity,
				r.RiskScore,
			)
		}
		fmt.Fprintln(w)
	}

	// Modified risks
	if len(diff.ModifiedRisks) > 0 {
		fmt.Fprintf(w, "%s (%d modified):\n", yellow("⚡ Modified Resource Risks"), len(diff.ModifiedRisks))
		for _, m := range diff.ModifiedRisks {
			fmt.Fprintf(w, "  ~ %s: %s -> %s | score %d -> %d\n",
				m.Address,
				m.BeforeSeverity,
				m.AfterSeverity,
				m.BeforeScore,
				m.AfterScore,
			)
		}
		fmt.Fprintln(w)
	}

	if len(diff.ResolvedRisks) == 0 && len(diff.NewRisks) == 0 && len(diff.ModifiedRisks) == 0 {
		fmt.Fprintln(w, gray("No significant risk deltas detected between both execution plans."))
	}

	return nil
}

// RenderDiffMarkdown formats differential blast analysis as Markdown for PR comments.
func RenderDiffMarkdown(w io.Writer, diff *analyzer.DiffReport) error {
	if diff == nil {
		return nil
	}

	fmt.Fprintln(w, "### 📊 tf-blast: Plan Comparison & Risk Delta")
	fmt.Fprintln(w)

	radiusSign := fmt.Sprintf("%+d", diff.RadiusDelta)
	scoreSign := fmt.Sprintf("%+d", diff.ScoreDelta)
	changesSign := fmt.Sprintf("%+d", diff.ChangesDelta)

	fmt.Fprintf(w, "| Metric | Previous Plan | Current Plan | Delta |\n")
	fmt.Fprintf(w, "| :--- | :--- | :--- | :--- |\n")
	fmt.Fprintf(w, "| **Blast Radius** | %d | %d | `%s` |\n", diff.BeforeSummary.TotalBlastRadius, diff.AfterSummary.TotalBlastRadius, radiusSign)
	fmt.Fprintf(w, "| **Blast Score** | %d | %d | `%s` |\n", diff.BeforeSummary.BlastScore, diff.AfterSummary.BlastScore, scoreSign)
	fmt.Fprintf(w, "| **Total Changes** | %d | %d | `%s` |\n\n", diff.BeforeSummary.TotalChanges, diff.AfterSummary.TotalChanges, changesSign)

	if len(diff.ResolvedRisks) > 0 {
		fmt.Fprintf(w, "#### ✅ Mitigated / Resolved Risks (%d)\n\n", len(diff.ResolvedRisks))
		for _, r := range diff.ResolvedRisks {
			fmt.Fprintf(w, "- **Resolved:** `%s` (`%s` was %s)\n", r.Address, r.Severity, r.Action)
		}
		fmt.Fprintln(w)
	}

	if len(diff.NewRisks) > 0 {
		fmt.Fprintf(w, "#### ⚠️ Newly Introduced Risks (%d)\n\n", len(diff.NewRisks))
		for _, r := range diff.NewRisks {
			fmt.Fprintf(w, "- **New:** `%s` (`%s`, %s, score +%d)\n", r.Address, r.Severity, r.Action, r.RiskScore)
		}
		fmt.Fprintln(w)
	}

	if len(diff.ModifiedRisks) > 0 {
		fmt.Fprintf(w, "#### ⚡ Modified Risk Profile (%d)\n\n", len(diff.ModifiedRisks))
		for _, m := range diff.ModifiedRisks {
			fmt.Fprintf(w, "- `%s`: %s -> %s (score %d -> %d)\n", m.Address, m.BeforeSeverity, m.AfterSeverity, m.BeforeScore, m.AfterScore)
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "_Comparative analysis generated by [tf-blast](https://github.com/smford/tf-blast)_")
	return nil
}

// RenderDiffJSON outputs structured JSON for diff report.
func RenderDiffJSON(w io.Writer, diff *analyzer.DiffReport) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(diff)
}
