package renderer

import (
	"fmt"
	"io"
	"strings"

	"github.com/smford/tf-blast/pkg/analyzer"
)

// RenderMarkdown outputs a clean, GitHub/GitLab-ready Markdown report to io.Writer.
func RenderMarkdown(w io.Writer, report *analyzer.AnalysisReport) error {
	if report == nil {
		return nil
	}

	fmt.Fprintln(w, "### 💥 tf-blast: Blast-Radius & Risk Report")
	fmt.Fprintln(w)

	// Health status banner
	var healthBadge string
	switch report.Summary.MaxSeverity {
	case analyzer.SeverityCritical:
		healthBadge = "🚨 **" + report.Summary.PlanHealth + "**"
	case analyzer.SeverityHigh:
		healthBadge = "⚠️ **" + report.Summary.PlanHealth + "**"
	case analyzer.SeverityMedium:
		healthBadge = "⚡ **" + report.Summary.PlanHealth + "**"
	default:
		healthBadge = "✅ **" + report.Summary.PlanHealth + "**"
	}
	fmt.Fprintf(w, "**Plan Health:** %s\n\n", healthBadge)

	// Summary metrics
	fmt.Fprintf(w, "**Summary:** `+%d` to add | `~%d` to update | `-%d` to destroy | `±%d` to replace\n\n",
		report.Summary.ToAdd,
		report.Summary.ToUpdate,
		report.Summary.ToDestroy,
		report.Summary.ToReplace,
	)
	fmt.Fprintf(w, "**Total Blast Radius:** %d affected resource(s)\n\n", report.Summary.TotalBlastRadius)
	if report.Summary.DriftCount > 0 {
		fmt.Fprintf(w, "> [!WARNING]\n> **Out-of-Band State Drift Detected:** %d resource(s) were modified directly in the cloud console or drifted from state.\n\n", report.Summary.DriftCount)
	}

	if report.Failed {
		fmt.Fprintf(w, "> [!CAUTION]\n> **Policy Check Failed:** %s\n\n", report.FailReason)
	}

	if len(report.Resources) == 0 {
		fmt.Fprintln(w, "_No modified resources found in execution plan._")
		return nil
	}

	// Main table
	fmt.Fprintln(w, "| Impact Level | Resource Address | Planned Action | Root Cause Attribute | Downstream Affected |")
	fmt.Fprintln(w, "| :--- | :--- | :--- | :--- | :--- |")

	for _, res := range report.Resources {
		impactBadge := formatMarkdownSeverity(res.Severity)
		actionBadge := formatMarkdownAction(res.Action)

		addrStr := fmt.Sprintf("`%s`", res.Address)
		if res.HasDrift {
			addrStr += " ⚠️ *(drifted)*"
		}

		downstreamStr := "-"
		if res.DownstreamCount > 0 {
			downstreamStr = formatDownstreamDesc(res.DownstreamCount, res.Type)
		}

		rcStr := res.RootCause
		if rcStr == "" {
			rcStr = "-"
		} else if !strings.Contains(rcStr, "`") && rcStr != "-" && rcStr != "Dropped in PR" && rcStr != "Net-new resource" {
			rcStr = fmt.Sprintf("`%s`", rcStr)
		}

		fmt.Fprintf(w, "| %s | %s | %s | %s | %s |\n",
			impactBadge,
			addrStr,
			actionBadge,
			rcStr,
			downstreamStr,
		)
	}
	fmt.Fprintln(w)

	// Collapsible Cascading Trees
	hasTrees := false
	for _, res := range report.Resources {
		if res.DownstreamTree != nil && len(res.DownstreamTree.Children) > 0 {
			hasTrees = true
			break
		}
	}

	if hasTrees {
		fmt.Fprintln(w, "<details>")
		fmt.Fprintln(w, "<summary>🔍 <strong>View Cascading Blast Radius Graph</strong></summary>")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "#### Visual Architecture Graph")
		_ = RenderMermaid(w, report)
		fmt.Fprintln(w)
		fmt.Fprintln(w, "#### Impact Tree Hierarchy")
		fmt.Fprintln(w, "```text")
		for _, res := range report.Resources {
			if res.DownstreamTree != nil && len(res.DownstreamTree.Children) > 0 {
				fmt.Fprint(w, res.DownstreamTree.RenderTree())
				fmt.Fprintln(w)
			}
		}
		fmt.Fprintln(w, "```")
		fmt.Fprintln(w, "</details>")
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "_Generated by [tf-blast](https://github.com/smford/tf-blast) • Zero-Trust Blast Radius Analysis_")

	return nil
}

func formatMarkdownSeverity(s analyzer.Severity) string {
	switch s {
	case analyzer.SeverityCritical:
		return "🔴 CRITICAL"
	case analyzer.SeverityHigh:
		return "🟠 HIGH"
	case analyzer.SeverityMedium:
		return "🟡 MEDIUM"
	case analyzer.SeverityLow:
		return "🟢 LOW"
	default:
		return "⚪ CLEAN"
	}
}

func formatMarkdownAction(a analyzer.ActionType) string {
	switch a {
	case analyzer.ActionReplace:
		return "**REPLACE**"
	case analyzer.ActionDestroy:
		return "**DESTROY**"
	case analyzer.ActionUpdateInPlace:
		return "UPDATE"
	case analyzer.ActionCreate:
		return "CREATE"
	default:
		return string(a)
	}
}

func formatDownstreamDesc(count int, resType string) string {
	lower := strings.ToLower(resType)
	if strings.Contains(lower, "database") || strings.Contains(lower, "rds") {
		return fmt.Sprintf("%d services", count)
	}
	if strings.Contains(lower, "security_group") || strings.Contains(lower, "subnet") || strings.Contains(lower, "vpc") {
		return fmt.Sprintf("%d instances", count)
	}
	return fmt.Sprintf("%d resources", count)
}
